"""empty message

Revision ID: e2ce17842034
Revises: 81234ac5b4cb
Create Date: 2022-03-05 06:18:07.537265

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e2ce17842034'
down_revision = '81234ac5b4cb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('words', 'type')
    op.drop_column('words', 'lang')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('words', sa.Column('lang', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('words', sa.Column('type', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
